// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "moveArm.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

moveArm::moveArm(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::cobraArmSystem.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void moveArm::Initialize() {
	Robot::cobraArmSystem->MovePrimaryArm(0);
	Robot::cobraArmSystem->MoveSecondaryArm(0);
	SmartDashboard::PutString("Running Arm", "ya");
}

// Called repeatedly when this Command is scheduled to run
void moveArm::Execute() {
	Robot::cobraArmSystem->MovePrimaryArm(Robot::oi->GetOtherY1());
	Robot::cobraArmSystem->MoveSecondaryArm(Robot::oi->GetOtherY2());
	SmartDashboard::PutString("Running Arm", "ya");
	SmartDashboard::PutNumber("CObra Arm prim value", Robot::oi->GetOtherY1());
	SmartDashboard::PutNumber("CObra Arm sec value", Robot::oi->GetOtherY2());
}

// Make this return true when this Command no longer needs to run execute()
bool moveArm::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void moveArm::End() {
	Robot::cobraArmSystem->MovePrimaryArm(0);
	Robot::cobraArmSystem->MoveSecondaryArm(0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void moveArm::Interrupted() {
	Robot::cobraArmSystem->MovePrimaryArm(0);
	Robot::cobraArmSystem->MoveSecondaryArm(0);
}
