// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveLeftDrive;
std::shared_ptr<CANTalon> RobotMap::driveRightDrive;
std::shared_ptr<RobotDrive> RobotMap::driveTankDrive;
std::shared_ptr<CANTalon> RobotMap::intakeSubsystemIntakeTalon;
std::shared_ptr<Servo> RobotMap::intakeSubsystemServoLeft;
std::shared_ptr<Servo> RobotMap::intakeSubsystemServoRight;
std::shared_ptr<CANTalon> RobotMap::shooterSystemShooterRight;
std::shared_ptr<CANTalon> RobotMap::shooterSystemShooterLeft;
std::shared_ptr<CANTalon> RobotMap::lifterSystemWindowMotor;
std::shared_ptr<CANTalon> RobotMap::lifterSystemWinch;
std::shared_ptr<CANTalon> RobotMap::cobraArmSystemPrimaryMotor;
std::shared_ptr<CANTalon> RobotMap::cobraArmSystemSecondaryMotor;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveLeftDrive.reset(new CANTalon(3));
    lw->AddActuator("Drive", "LeftDrive", driveLeftDrive);
    
    driveRightDrive.reset(new CANTalon(5));
    lw->AddActuator("Drive", "RightDrive", driveRightDrive);
    
    driveTankDrive.reset(new RobotDrive(driveLeftDrive, driveRightDrive));
    
    driveTankDrive->SetSafetyEnabled(true);
        driveTankDrive->SetExpiration(0.1);
        driveTankDrive->SetSensitivity(0.5);
        driveTankDrive->SetMaxOutput(1.0);

    intakeSubsystemIntakeTalon.reset(new CANTalon(1));
    lw->AddActuator("IntakeSubsystem", "IntakeTalon", intakeSubsystemIntakeTalon);
    
    intakeSubsystemServoLeft.reset(new Servo(1));
    lw->AddActuator("IntakeSubsystem", "ServoLeft", intakeSubsystemServoLeft);
    
    intakeSubsystemServoRight.reset(new Servo(0));
    lw->AddActuator("IntakeSubsystem", "ServoRight", intakeSubsystemServoRight);
    
    shooterSystemShooterRight.reset(new CANTalon(4));
    lw->AddActuator("ShooterSystem", "ShooterRight", shooterSystemShooterRight);
    
    shooterSystemShooterLeft.reset(new CANTalon(2));
    lw->AddActuator("ShooterSystem", "ShooterLeft", shooterSystemShooterLeft);
    
    lifterSystemWindowMotor.reset(new CANTalon(7));
    lw->AddActuator("LifterSystem", "WindowMotor", lifterSystemWindowMotor);
    
    lifterSystemWinch.reset(new CANTalon(17)); //fix number
    lw->AddActuator("LifterSystem", "Winch", lifterSystemWinch);
    
    cobraArmSystemPrimaryMotor.reset(new CANTalon(6));
    lw->AddActuator("CobraArmSystem", "PrimaryMotor", cobraArmSystemPrimaryMotor);
    
    cobraArmSystemSecondaryMotor.reset(new CANTalon(8));
    lw->AddActuator("CobraArmSystem", "SecondaryMotor", cobraArmSystemSecondaryMotor);
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
